#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --exclusive

# Get the source 
wget https://www.netlib.org/benchmark/hpl/hpl-2.3.tar.gz
tar -xzf hpl-2.3.tar.gz
cd hpl-2.3

# Set up our environment to run with Intel-oneapi. 
# However, we are not using MKL here

module purge
for m in                                   \
		craype-x86-spr \
		gcc-native/12.1 \
		craype/2.7.30 \
		cray-dsmml/0.2.2 \
		libfabric/1.15.2.0 \
		craype-network-ofi \
		cray-mpich/8.1.28 \
		cray-libsci/23.12.5 \
		PrgEnv-gnu/8.5.0 \
		intel-oneapi-tbb/2021.10.0-intel  \
		intel-oneapi-mkl/2024.0.0-intel  \
         ;do
         module load $m
done





module list
 
# Use configure instead of the make include files because they are all very old
# We need to point to the directory containing openblas
export LDFLAGS=-L/nopt/nrel/apps/cpu_stack/libraries-gcc/06-24/linux-rhel8-sapphirerapids/gcc-12.3.0/openblas-0.3.26-vj5oijqgam3umrmecc2fns4pzwf36bya/lib
./configure --prefix=`pwd`
make clean
make
make install

# Grab the executable directory
cp bin/xhpl $SLURM_SUBMIT_DIR

# Go "home"
cd $SLURM_SUBMIT_DIR

# Create an small test case input file

echo "Input generated using the form at https://www.advancedclustering.com/act_kb/tune-hpl-dat-file/"
echo With:
echo Nodes:               2
echo Cores per node:     10
echo Memory per Node: 24000
echo Block Size:        192


cat << SMALL > HPL.dat
HPLinpack benchmark input file
Innovative Computing Laboratory, University of Tennessee
HPL.out      output file name (if any) 
6            device out (6=stdout,7=stderr,file)
1            # of problems sizes (N)
49920         Ns
1            # of NBs
192           NBs
0            PMAP process mapping (0=Row-,1=Column-major)
1            # of process grids (P x Q)
4            Ps
5            Qs
16.0         threshold
1            # of panel fact
2            PFACTs (0=left, 1=Crout, 2=Right)
1            # of recursive stopping criterium
4            NBMINs (>= 1)
1            # of panels in recursion
2            NDIVs
1            # of recursive panel fact.
1            RFACTs (0=left, 1=Crout, 2=Right)
1            # of broadcast
1            BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
1            # of lookahead depth
1            DEPTHs (>=0)
2            SWAP (0=bin-exch,1=long,2=mix)
64           swapping threshold
0            L1 in (0=transposed,1=no-transposed) form
0            U  in (0=transposed,1=no-transposed) form
1            Equilibration (0=no,1=yes)
8            memory alignment in double (> 0)
##### This line (no. 32) is ignored (it serves as a separator). ######
0                               Number of additional problem sizes for PTRANS
1200 10000 30000                values of N
0                               number of additional blocking sizes for PTRANS
40 9 8 13 13 20 16 32 64        values of NB
SMALL
srun -n 20 --tasks-per-node=10 ./xhpl > small.out

